--- #YAML:1.0
name:               PDL-Stats
version:            0.4.4
abstract:           a collection of statistics modules in Perl Data Language, with a quick-start guide for non-PDL people.
author:
    - Maggie J. Xiong  <maggiexyz users.sourceforge.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL::Lite:   
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
